name: CI

on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Run tests
      run: |
        export PYTHONPATH=src/modules
        python -m unittest discover tests
    - name: Build zip
      run: |
        mkdir dist
        mkdir dist/pyscript
        cp -R src/* dist/pyscript/
        cd dist
        zip -r agile-powerwall.zip * -x "*/__pycache__/*" "*/__pycache__/"
    - name: Release zips
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/agile-powerwall.zip
