name: CI

on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Run tests
      run: |
        export PYTHONPATH=src/modules
        python -m unittest discover tests
